/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gwenod.gd.service.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the GestionDocument service. Represents a row in the &quot;_gestdoc&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gwenod.gd.service.model.impl.GestionDocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gwenod.gd.service.model.impl.GestionDocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GestionDocument
 * @generated
 */
@ProviderType
public interface GestionDocumentModel extends BaseModel<GestionDocument> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gestion document model instance should use the {@link GestionDocument} interface instead.
	 */

	/**
	 * Returns the primary key of this gestion document.
	 *
	 * @return the primary key of this gestion document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gestion document.
	 *
	 * @param primaryKey the primary key of this gestion document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this gestion document.
	 *
	 * @return the ID of this gestion document
	 */
	public long getId();

	/**
	 * Sets the ID of this gestion document.
	 *
	 * @param id the ID of this gestion document
	 */
	public void setId(long id);

	@Override
	public GestionDocument cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}