/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gwenod.gestiondocuments.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Document service. Represents a row in the &quot;GDDocument&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gwenod.gestiondocuments.service.model.impl.DocumentModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gwenod.gestiondocuments.service.model.impl.DocumentImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Document
 * @generated
 */
@ProviderType
public interface DocumentModel
	extends BaseModel<Document>, GroupedModel, ShardedModel,
			StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document model instance should use the {@link Document} interface instead.
	 */

	/**
	 * Returns the primary key of this document.
	 *
	 * @return the primary key of this document
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document.
	 *
	 * @param primaryKey the primary key of this document
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this document.
	 *
	 * @return the uuid of this document
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this document.
	 *
	 * @param uuid the uuid of this document
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the document ID of this document.
	 *
	 * @return the document ID of this document
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document.
	 *
	 * @param documentId the document ID of this document
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the group ID of this document.
	 *
	 * @return the group ID of this document
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this document.
	 *
	 * @param groupId the group ID of this document
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this document.
	 *
	 * @return the company ID of this document
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this document.
	 *
	 * @param companyId the company ID of this document
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this document.
	 *
	 * @return the user ID of this document
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this document.
	 *
	 * @param userId the user ID of this document
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this document.
	 *
	 * @return the user uuid of this document
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this document.
	 *
	 * @param userUuid the user uuid of this document
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this document.
	 *
	 * @return the user name of this document
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this document.
	 *
	 * @param userName the user name of this document
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this document.
	 *
	 * @return the create date of this document
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this document.
	 *
	 * @param createDate the create date of this document
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this document.
	 *
	 * @return the modified date of this document
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this document.
	 *
	 * @param modifiedDate the modified date of this document
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the modified by of this document.
	 *
	 * @return the modified by of this document
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this document.
	 *
	 * @param modifiedBy the modified by of this document
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the city of this document.
	 *
	 * @return the city of this document
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this document.
	 *
	 * @param city the city of this document
	 */
	public void setCity(String city);

	/**
	 * Returns the address of this document.
	 *
	 * @return the address of this document
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this document.
	 *
	 * @param address the address of this document
	 */
	public void setAddress(String address);

	/**
	 * Returns the type of this document.
	 *
	 * @return the type of this document
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this document.
	 *
	 * @param type the type of this document
	 */
	public void setType(String type);

	/**
	 * Returns the description of this document.
	 *
	 * @return the description of this document
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this document.
	 *
	 * @param description the description of this document
	 */
	public void setDescription(String description);

	/**
	 * Returns the title of this document.
	 *
	 * @return the title of this document
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this document.
	 *
	 * @param title the title of this document
	 */
	public void setTitle(String title);

	/**
	 * Returns the filepath of this document.
	 *
	 * @return the filepath of this document
	 */
	@AutoEscape
	public String getFilepath();

	/**
	 * Sets the filepath of this document.
	 *
	 * @param filepath the filepath of this document
	 */
	public void setFilepath(String filepath);

	/**
	 * Returns the filename of this document.
	 *
	 * @return the filename of this document
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this document.
	 *
	 * @param filename the filename of this document
	 */
	public void setFilename(String filename);

	/**
	 * Returns the fileversion of this document.
	 *
	 * @return the fileversion of this document
	 */
	public long getFileversion();

	/**
	 * Sets the fileversion of this document.
	 *
	 * @param fileversion the fileversion of this document
	 */
	public void setFileversion(long fileversion);

	/**
	 * Returns the tags of this document.
	 *
	 * @return the tags of this document
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this document.
	 *
	 * @param tags the tags of this document
	 */
	public void setTags(String tags);

	@Override
	public Document cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}