/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.gwenod.gestiondocuments.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DocumentHistory service. Represents a row in the &quot;GDHistory&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.gwenod.gestiondocuments.service.model.impl.DocumentHistoryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.gwenod.gestiondocuments.service.model.impl.DocumentHistoryImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see DocumentHistory
 * @generated
 */
@ProviderType
public interface DocumentHistoryModel extends BaseModel<DocumentHistory> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a document history model instance should use the {@link DocumentHistory} interface instead.
	 */

	/**
	 * Returns the primary key of this document history.
	 *
	 * @return the primary key of this document history
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this document history.
	 *
	 * @param primaryKey the primary key of this document history
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this document history.
	 *
	 * @return the uuid of this document history
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this document history.
	 *
	 * @param uuid the uuid of this document history
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the history ID of this document history.
	 *
	 * @return the history ID of this document history
	 */
	public long getHistoryId();

	/**
	 * Sets the history ID of this document history.
	 *
	 * @param historyId the history ID of this document history
	 */
	public void setHistoryId(long historyId);

	/**
	 * Returns the version date of this document history.
	 *
	 * @return the version date of this document history
	 */
	public Date getVersionDate();

	/**
	 * Sets the version date of this document history.
	 *
	 * @param versionDate the version date of this document history
	 */
	public void setVersionDate(Date versionDate);

	/**
	 * Returns the version modifier of this document history.
	 *
	 * @return the version modifier of this document history
	 */
	public long getVersionModifier();

	/**
	 * Sets the version modifier of this document history.
	 *
	 * @param versionModifier the version modifier of this document history
	 */
	public void setVersionModifier(long versionModifier);

	/**
	 * Returns the document ID of this document history.
	 *
	 * @return the document ID of this document history
	 */
	public long getDocumentId();

	/**
	 * Sets the document ID of this document history.
	 *
	 * @param documentId the document ID of this document history
	 */
	public void setDocumentId(long documentId);

	/**
	 * Returns the title of this document history.
	 *
	 * @return the title of this document history
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this document history.
	 *
	 * @param title the title of this document history
	 */
	public void setTitle(String title);

	/**
	 * Returns the filepath of this document history.
	 *
	 * @return the filepath of this document history
	 */
	@AutoEscape
	public String getFilepath();

	/**
	 * Sets the filepath of this document history.
	 *
	 * @param filepath the filepath of this document history
	 */
	public void setFilepath(String filepath);

	/**
	 * Returns the filename of this document history.
	 *
	 * @return the filename of this document history
	 */
	@AutoEscape
	public String getFilename();

	/**
	 * Sets the filename of this document history.
	 *
	 * @param filename the filename of this document history
	 */
	public void setFilename(String filename);

	/**
	 * Returns the fileversion of this document history.
	 *
	 * @return the fileversion of this document history
	 */
	public long getFileversion();

	/**
	 * Sets the fileversion of this document history.
	 *
	 * @param fileversion the fileversion of this document history
	 */
	public void setFileversion(long fileversion);

	/**
	 * Returns the tags of this document history.
	 *
	 * @return the tags of this document history
	 */
	@AutoEscape
	public String getTags();

	/**
	 * Sets the tags of this document history.
	 *
	 * @param tags the tags of this document history
	 */
	public void setTags(String tags);

	/**
	 * Returns the city of this document history.
	 *
	 * @return the city of this document history
	 */
	@AutoEscape
	public String getCity();

	/**
	 * Sets the city of this document history.
	 *
	 * @param city the city of this document history
	 */
	public void setCity(String city);

	/**
	 * Returns the address of this document history.
	 *
	 * @return the address of this document history
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this document history.
	 *
	 * @param address the address of this document history
	 */
	public void setAddress(String address);

	/**
	 * Returns the description of this document history.
	 *
	 * @return the description of this document history
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this document history.
	 *
	 * @param description the description of this document history
	 */
	public void setDescription(String description);

	@Override
	public DocumentHistory cloneWithOriginalValues();

	public default String toXmlString() {
		return null;
	}

}