info:
  description: "GestionDocumentsRest REST API"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
  title: "GestionDocumentsRest"
  version: v1.0
openapi: 3.0.1
components:
  schemas:
    File:
      type: object
      properties:
        fileName:
          type: string
        filePath:
          type: string
          format: uri
        fileVersion:
          type: integer
          format: int64
    Document:
      type: object
      properties:
        documentId:
          type: integer
          format: int64
        title:
          type: string
        city:
          type: string
        address:
          type: string
        type:
          type: string
          enum: [ "POA", "POI" ]
        tags:
          type: array
          items:
            type: string
        file:
          $ref: '#/components/schemas/File'
        createDate:
          type: string
          format: date-time
        modifiedDate:
          type: string
          format: date-time
    DocumentHistory:
      type: object
      properties:
        historyId:
          type: integer
          format: int64
        title:
          type: string
        city:
          type: string
        address:
          type: string
        tags:
          type: array
          items:
            type: string
        file:
          $ref: '#/components/schemas/File'
        versionDate:
          type: string
          format: date-time
        versionModifier:
          type: integer
          format: int64

    Error:
      type: object
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
        fieldErrors:
          type: array
          items:
            $ref: '#/components/schemas/FieldError'
    FieldError:
      type: object
      properties:
        name:
          type: string
        message:
          type: string

    DocumentCreationRequest:
      type: object
      properties:
        title:
          type: string
        city:
          type: string
        address:
          type: string
        type:
          type: string
          enum:
            - "POA"
            - "POI"
        tags:
          type: array
          items:
            type: string
        items:
          type: string
        filename:
          type: string
        file:
          type: string
          format: binary
      required: [ "title", "city", "address", "type", "file" ]
paths:
  "/document":
    post:
      operationId: createDocument
      summary: "Create a document"
      tags: [ "Document" ]
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/DocumentCreationRequest"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"

        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
  "/document/{documentId}":
    get:
      operationId: getDocument
      summary: "Get a document"
      tags: [ "Document" ]
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
        404:
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
    put:
      operationId: updateDocument
      summary: "Update a document"
      tags: [ "Document" ]
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              $ref: "#/components/schemas/DocumentCreationRequest"
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
        404:
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
    delete:
      operationId: deleteDocument
      summary: "Delete a document"
      tags: [ "Document" ]
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
        404:
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
  "/document/{documentId}/file":
    get:
      operationId: getDocumentFile
      summary: "Get a document file"
      tags: [ "Document" ]
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "OK"
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary

  "/document/{documentId}/history":
    get:
      operationId: getDocumentHistory
      summary: "Get a document history"
      tags: [ "Document" ]
      parameters:
        - name: documentId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
        404:
          description: "Not Found"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
  "/documents":
    get:
      operationId: getDocuments
      summary: "Get documents"
      tags: [ "Document" ]
      parameters:
        - name: title
          in: query
          required: false
          schema:
            type: string
        - name: tags
          in: query
          required: false
          schema:
            type: array
            items:
              type: string

      responses:
        200:
          description: "OK"
          content:
            application/json:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                oneOf:
                  - type: array
                    items:
                      $ref: "#/components/schemas/Document"
                  - $ref: "#/components/schemas/Error"

        500:
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
            application/xml:
              schema:
                $ref: "#/components/schemas/Error"
