apiDir: "../gestion-documents-rest-api/src/main/java"
apiPackagePath: "com.liferay.gwenod.rest"
application:
  baseURI: "/gestion-documents-rest"
  className: "GestionDocumentsRestApplication"
  name: "GestionDocumentsRest"
author: "elbou"
clientDir: "../gestion-documents-rest-client/src/main/java"
testDir: "../gestion-documents-rest-test/src/testIntegration/java"
generateGraphQL: false